source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.3'

target 'MonthYearPicker_Example' do
  pod 'MonthYearPicker', :path => '../'
end

target 'MonthYearPicker_Tests' do
  pod 'MonthYearPicker', :path => '../'
end
